# Generated by Django 5.0.3 on 2024-04-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_rename_body_blogpost_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_date',
        ),
    ]
